import { TaskData } from "../types/types";

export const tasksData: TaskData[] = [
  {
    id: '1',
    taskName: 'Send Quote to Dupont',
    linkedTo: 'Deal – Maison Dupont',
    assignedTo: 'Claire Brunet',
    assignedImage: 'https://i.pravatar.cc/32?img=1',
    status: 'To-Do',
    priority: 'High',
    dueDate: 'June 01, 2025',
    lastUpdate: '3h ago',
  },
  {
    id: '2',
    taskName: 'Call ABC Construction',
    linkedTo: 'Company – ABC Construction',
    assignedTo: 'Thomas Delcourt',
    assignedImage: 'https://i.pravatar.cc/32?img=2',
    status: 'In-Progress',
    priority: 'Urgent',
    dueDate: 'June 01, 2025',
    lastUpdate: 'May 28, 2025',
  },
  {
    id: '3',
    taskName: 'Upload Documents',
    linkedTo: 'Contact – Sophie L.',
    assignedTo: 'Claire Brunet',
    assignedImage: 'https://i.pravatar.cc/32?img=3',
    status: 'Done',
    priority: 'Low',
    dueDate: 'June 01, 2025',
    lastUpdate: '2h ago',
  },
  {
    id: '4',
    taskName: 'Site Visit Prep',
    linkedTo: 'Deal – Projet Alpha',
    assignedTo: 'Thomas Delcourt',
    assignedImage: 'https://i.pravatar.cc/32?img=4',
    status: 'On-Hold',
    priority: 'Medium',
    dueDate: 'June 01, 2025',
    lastUpdate: '5h ago',
  },
  {
    id: '5',
    taskName: 'Review Contract Draft',
    linkedTo: 'Company – AEC Partners',
    assignedTo: 'Claire Brunet',
    assignedImage: 'https://i.pravatar.cc/32?img=5',
    status: 'To-Do',
    priority: 'High',
    dueDate: 'June 01, 2025',
    lastUpdate: 'Yesterday',
  },
  {
    id: '6',
    taskName: 'Prepare Kickoff Deck',
    linkedTo: 'Company – NovaTech',
    assignedTo: 'Daniel Prieto',
    assignedImage: 'https://i.pravatar.cc/32?img=6',
    status: 'In-Progress',
    priority: 'High',
    dueDate: 'June 01, 2025',
    lastUpdate: 'Yesterday',
  },
  {
    id: '7',
    taskName: 'Finalize Homepage Wireframe',
    linkedTo: 'Company – Flashcar',
    assignedTo: 'Daniel Prieto',
    assignedImage: 'https://i.pravatar.cc/32?img=7',
    status: 'In-Progress',
    priority: 'Medium',
    dueDate: 'June 01, 2025',
    lastUpdate: 'Yesterday',
  },
  {
    id: '8',
    taskName: 'Compile User Research Notes',
    linkedTo: 'Company – AWSMD Design',
    assignedTo: 'Claire Brunet',
    assignedImage: 'https://i.pravatar.cc/32?img=8',
    status: 'Done',
    priority: 'Low',
    dueDate: 'June 01, 2025',
    lastUpdate: '2h ago',
  },
]
